# Generated by Django 3.2.7 on 2024-03-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('Product_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Product_name', models.CharField(max_length=200)),
                ('Product_price', models.CharField(max_length=200)),
                ('Product_caption', models.CharField(max_length=200)),
                ('Product_image', models.ImageField(blank=True, null=True, upload_to='turf_img')),
                ('Product_area', models.CharField(choices=[('Calicut', 'Calicut'), ('Malappuram', 'Malappuram')], default='Calicut', max_length=200)),
            ],
        ),
    ]
