# Generated by Django 3.2.7 on 2024-03-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0004_alter_merchantprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantprofile',
            name='Phone_Number',
            field=models.IntegerField(),
        ),
    ]
