# Generated by Django 3.2.7 on 2024-03-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0005_alter_merchantprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='Product_area',
            field=models.CharField(choices=[('construction', 'construction'), ('electricals', 'electricals'), ('plumbing', 'plumbing'), ('interior', 'interior'), ('paint', 'paint'), ('courtyard', 'courtyard')], default='con', max_length=200),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='Product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_img'),
        ),
    ]
