# Generated by Django 3.2.7 on 2024-03-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0006_auto_20240307_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='Product_area',
            field=models.CharField(choices=[('construction', 'construction'), ('electricals', 'electricals'), ('plumbing', 'plumbing'), ('interior', 'interior'), ('paint', 'paint'), ('courtyard', 'courtyard')], default='construction', max_length=200),
        ),
    ]
